import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/app/context/AuthContext';
import Header from '@/app/components/Organisms/header'; 
import Footer from '@/app/components/Organisms/footer'; 
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
        <Header />
          {children}
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
